apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: ironfang26/backend:latest

          ports:
            - containerPort: 3000

          env:
            - name: DB_HOST
              value: "todoappdocker.chsiiwmc8nse.us-west-2.rds.amazonaws.com"

            - name: DB_USER
              value: "admin"

            - name: DB_PASSWORD
              value: "admin12345"

            - name: DB_NAME
              value: "todoappdocker"

            - name: DB_PORT
              value: "3306"

            - name: PORT
              value: "3000"
